SET request.jwt.claim.role = 'service_role';

-- Generic, reusable "auto-fed" rule engine -- replaces the Niksen/entities-
-- specific niksen_recompute_entity_irregularities()/niksen_upsert_irregularity()
-- pair (see 20260729040000 and follow-ups) with a config-driven system any
-- future auto-populated registry table can plug into by inserting rows,
-- not writing new trigger functions.
--
-- auto_fed_registries: one row per "watched source -> target table" link
-- (e.g. watch entities, write violations into the Irregularities table).
-- auto_fed_rules: one row per rule within a registry -- condition_sql is a
-- boolean SQL expression evaluated with the watched row aliased `r`
-- (`SELECT (<condition_sql>) FROM <source_table_name> r WHERE r.id = $1`),
-- so a rule can reference joins/subqueries against any other table freely,
-- same as niksen's original rules did inline. This is trusted, developer-
-- authored config (inserted by migrations, not exposed to end users to type
-- freely), same trust level as any other migration SQL -- not a general
-- "let users write SQL" feature.
--
-- The target (auto-fed) table itself must follow a fixed field_key
-- convention: issue_type/classification/detail/status/detected_at/
-- source_table/target_field_key (all 'text' except detected_at 'date'),
-- plus one relation field whose field_type matches the source
-- (entity/project/property) linking each row back to what triggered it --
-- see auto_fed_upsert_item's resolution below. This is what lets the
-- engine work against ANY target table shaped this way, not just
-- Irregularities.

-- page_kind is the "different type of table" distinction requested --
-- orthogonal to base_table (which picks WHERE an item's data lives).
-- 'user_dependent' (default) = staff add/remove items and edit fields
-- freely, e.g. matters/entities boards. 'auto_fed' = items are entirely
-- system-generated by this rule engine -- no manual add, fields read-only
-- except whatever a registry's editable_field_keys allows (e.g. Status).
ALTER TABLE client_update_pages ADD COLUMN IF NOT EXISTS page_kind text NOT NULL DEFAULT 'user_dependent'
  CHECK (page_kind IN ('user_dependent', 'auto_fed'));

CREATE TABLE IF NOT EXISTS auto_fed_registries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  target_table_id uuid NOT NULL REFERENCES company_tables(id) ON DELETE CASCADE,
  source_table_name text NOT NULL,
  -- Source-table field_keys (native columns, or a company_custom_fields.id)
  -- that stay directly editable on the auto-fed board despite it otherwise
  -- being read-only-except-via-fix -- e.g. 'status', for ticking Open/
  -- Resolved by hand. See app/api/client-update-pages/[id]/values/route.ts.
  editable_field_keys text[] NOT NULL DEFAULT '{}',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (target_table_id)
);

CREATE TABLE IF NOT EXISTS auto_fed_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  registry_id uuid NOT NULL REFERENCES auto_fed_registries(id) ON DELETE CASCADE,
  rule_key text NOT NULL,
  label text NOT NULL,
  classification text NOT NULL,
  detail text NOT NULL,
  -- Native column name on the source table, a company_custom_fields.id, or
  -- a source-specific sentinel (e.g. 'trust_link') -- see
  -- app/api/client-update-pages/[id]/items/[itemId]/fix/route.ts for how
  -- this resolves into an actual editable field.
  target_field_key text,
  condition_sql text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (registry_id, rule_key)
);

ALTER TABLE auto_fed_registries ENABLE ROW LEVEL SECURITY;
ALTER TABLE auto_fed_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS auto_fed_registries_rw ON auto_fed_registries;
CREATE POLICY auto_fed_registries_rw ON auto_fed_registries FOR ALL
  USING (company_id IN (SELECT company_id FROM company_memberships WHERE user_id = auth.uid()))
  WITH CHECK (company_id IN (SELECT company_id FROM company_memberships WHERE user_id = auth.uid()));
DROP POLICY IF EXISTS auto_fed_rules_rw ON auto_fed_rules;
CREATE POLICY auto_fed_rules_rw ON auto_fed_rules FOR ALL
  USING (registry_id IN (SELECT id FROM auto_fed_registries WHERE company_id IN (SELECT company_id FROM company_memberships WHERE user_id = auth.uid())))
  WITH CHECK (registry_id IN (SELECT id FROM auto_fed_registries WHERE company_id IN (SELECT company_id FROM company_memberships WHERE user_id = auth.uid())));

-- is_valid_abn(abn text)/is_valid_acn(acn text) already exist in this
-- database (confirmed live -- they back entities' chk_valid_abn/chk_valid_acn
-- CHECK constraints from before this session) -- reused as-is below, not
-- redefined. Only is_valid_tfn is genuinely new (no DB constraint on
-- entities.tfn, confirmed by testing), added here with the same p_tfn-free
-- naming convention as those two.
CREATE OR REPLACE FUNCTION is_valid_tfn(tfn text) RETURNS boolean AS $$
DECLARE
  d text := regexp_replace(coalesce(tfn, ''), '\D', '', 'g');
  weights8 int[] := ARRAY[10,7,8,4,6,3,5,1];
  weights9 int[] := ARRAY[1,4,3,7,5,8,6,9,10];
  weights int[];
  digits int[];
  total int := 0;
BEGIN
  IF length(d) NOT IN (8, 9) THEN RETURN false; END IF;
  weights := CASE WHEN length(d) = 8 THEN weights8 ELSE weights9 END;
  FOR i IN 1..length(d) LOOP digits[i] := substring(d FROM i FOR 1)::int; END LOOP;
  FOR i IN 1..length(d) LOOP total := total + digits[i] * weights[i]; END LOOP;
  RETURN total % 11 = 0;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ── Generic upsert: opens/resolves one (linked record, rule) item on a target table ──
CREATE OR REPLACE FUNCTION auto_fed_upsert_item(p_registry auto_fed_registries, p_rule auto_fed_rules, p_record_id uuid, p_is_violated boolean) RETURNS void AS $$
DECLARE
  v_link_field_type text := CASE p_registry.source_table_name WHEN 'entities' THEN 'entity' WHEN 'projects' THEN 'project' WHEN 'properties' THEN 'property' ELSE 'entity' END;
  v_f_link uuid; v_f_issue uuid; v_f_class uuid; v_f_detail uuid; v_f_status uuid; v_f_detected uuid; v_f_source_table uuid; v_f_target_key uuid;
  v_target_record_id uuid;
  v_page_id uuid;
BEGIN
  SELECT id INTO v_f_link       FROM company_table_fields WHERE table_id = p_registry.target_table_id AND field_type = v_link_field_type AND deleted_at IS NULL LIMIT 1;
  SELECT id INTO v_f_issue      FROM company_table_fields WHERE table_id = p_registry.target_table_id AND field_key = 'issue_type' AND deleted_at IS NULL;
  SELECT id INTO v_f_class      FROM company_table_fields WHERE table_id = p_registry.target_table_id AND field_key = 'classification' AND deleted_at IS NULL;
  SELECT id INTO v_f_detail     FROM company_table_fields WHERE table_id = p_registry.target_table_id AND field_key = 'detail' AND deleted_at IS NULL;
  SELECT id INTO v_f_status     FROM company_table_fields WHERE table_id = p_registry.target_table_id AND field_key = 'status' AND deleted_at IS NULL;
  SELECT id INTO v_f_detected   FROM company_table_fields WHERE table_id = p_registry.target_table_id AND field_key = 'detected_at' AND deleted_at IS NULL;
  SELECT id INTO v_f_source_table FROM company_table_fields WHERE table_id = p_registry.target_table_id AND field_key = 'source_table' AND deleted_at IS NULL;
  SELECT id INTO v_f_target_key FROM company_table_fields WHERE table_id = p_registry.target_table_id AND field_key = 'target_field_key' AND deleted_at IS NULL;
  IF v_f_link IS NULL OR v_f_issue IS NULL OR v_f_class IS NULL OR v_f_detail IS NULL OR v_f_status IS NULL OR v_f_detected IS NULL THEN
    RETURN; -- target table doesn't follow the standard convention -- nothing this engine can do
  END IF;

  SELECT r.id INTO v_target_record_id
  FROM company_table_records r
  JOIN company_table_values vl ON vl.record_id = r.id AND vl.field_id = v_f_link AND vl.value_record_id = p_record_id
  JOIN company_table_values vi ON vi.record_id = r.id AND vi.field_id = v_f_issue AND vi.value_text = p_rule.label
  JOIN company_table_values vs ON vs.record_id = r.id AND vs.field_id = v_f_status AND vs.value_text = 'Open'
  WHERE r.table_id = p_registry.target_table_id AND r.deleted_at IS NULL
  LIMIT 1;

  IF p_is_violated THEN
    IF v_target_record_id IS NULL THEN
      INSERT INTO company_table_records (company_id, table_id) VALUES (p_registry.company_id, p_registry.target_table_id) RETURNING id INTO v_target_record_id;
      INSERT INTO company_table_values (company_id, table_id, record_id, field_id, value_record_id) VALUES (p_registry.company_id, p_registry.target_table_id, v_target_record_id, v_f_link, p_record_id);
      INSERT INTO company_table_values (company_id, table_id, record_id, field_id, value_text) VALUES (p_registry.company_id, p_registry.target_table_id, v_target_record_id, v_f_issue, p_rule.label);
      INSERT INTO company_table_values (company_id, table_id, record_id, field_id, value_text) VALUES (p_registry.company_id, p_registry.target_table_id, v_target_record_id, v_f_class, p_rule.classification);
      INSERT INTO company_table_values (company_id, table_id, record_id, field_id, value_text) VALUES (p_registry.company_id, p_registry.target_table_id, v_target_record_id, v_f_detail, p_rule.detail);
      INSERT INTO company_table_values (company_id, table_id, record_id, field_id, value_text) VALUES (p_registry.company_id, p_registry.target_table_id, v_target_record_id, v_f_status, 'Open');
      INSERT INTO company_table_values (company_id, table_id, record_id, field_id, value_date) VALUES (p_registry.company_id, p_registry.target_table_id, v_target_record_id, v_f_detected, now()::date);
      IF v_f_source_table IS NOT NULL THEN
        INSERT INTO company_table_values (company_id, table_id, record_id, field_id, value_text) VALUES (p_registry.company_id, p_registry.target_table_id, v_target_record_id, v_f_source_table, initcap(p_registry.source_table_name));
      END IF;
      IF v_f_target_key IS NOT NULL AND p_rule.target_field_key IS NOT NULL THEN
        INSERT INTO company_table_values (company_id, table_id, record_id, field_id, value_text) VALUES (p_registry.company_id, p_registry.target_table_id, v_target_record_id, v_f_target_key, p_rule.target_field_key);
      END IF;

      SELECT id INTO v_page_id FROM client_update_pages WHERE company_id = p_registry.company_id AND source_table_id = p_registry.target_table_id AND page_kind = 'auto_fed' LIMIT 1;
      IF v_page_id IS NOT NULL THEN
        INSERT INTO client_update_page_items (page_id, custom_record_id, display_order)
        VALUES (v_page_id, v_target_record_id, (SELECT COALESCE(MAX(display_order), 0) + 1 FROM client_update_page_items WHERE page_id = v_page_id));
      END IF;
    END IF;
  ELSE
    IF v_target_record_id IS NOT NULL THEN
      UPDATE company_table_values SET value_text = 'Resolved', updated_at = now() WHERE record_id = v_target_record_id AND field_id = v_f_status;
    END IF;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- ── Generic recompute: evaluates every active rule in one registry for one watched record ──
CREATE OR REPLACE FUNCTION auto_fed_recompute(p_registry_id uuid, p_record_id uuid) RETURNS void AS $$
DECLARE
  v_registry auto_fed_registries;
  v_rule auto_fed_rules;
  v_is_violated boolean;
BEGIN
  SELECT * INTO v_registry FROM auto_fed_registries WHERE id = p_registry_id AND is_active;
  IF NOT FOUND THEN RETURN; END IF;

  FOR v_rule IN SELECT * FROM auto_fed_rules WHERE registry_id = p_registry_id AND is_active ORDER BY display_order LOOP
    BEGIN
      EXECUTE format('SELECT (%s) FROM %I r WHERE r.id = $1', v_rule.condition_sql, v_registry.source_table_name) INTO v_is_violated USING p_record_id;
    EXCEPTION WHEN OTHERS THEN
      v_is_violated := NULL; -- a malformed rule (or the watched row no longer existing) never blocks the other rules
    END;
    PERFORM auto_fed_upsert_item(v_registry, v_rule, p_record_id, COALESCE(v_is_violated, false));
  END LOOP;
END;
$$ LANGUAGE plpgsql;

-- ── Generic trigger dispatcher: bound once per watched source table, fans
-- out to every active registry watching it (so a 2nd registry on the same
-- source table needs zero new trigger/function code, just config rows) ──
CREATE OR REPLACE FUNCTION auto_fed_dispatch() RETURNS trigger AS $$
DECLARE
  v_registry_id uuid;
  v_record_id uuid := COALESCE(NEW.id, OLD.id);
  v_company_id uuid := COALESCE(NEW.company_id, OLD.company_id);
BEGIN
  FOR v_registry_id IN SELECT id FROM auto_fed_registries WHERE source_table_name = TG_TABLE_NAME AND company_id = v_company_id AND is_active LOOP
    PERFORM auto_fed_recompute(v_registry_id, v_record_id);
  END LOOP;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_auto_fed_dispatch_entities ON entities;
CREATE TRIGGER trg_auto_fed_dispatch_entities
AFTER INSERT OR UPDATE ON entities
FOR EACH ROW EXECUTE FUNCTION auto_fed_dispatch();

-- entity_relationships is a junction table (no company_id of its own, and
-- never itself a registry's "source"), so it gets a small dedicated wrapper
-- rather than being dispatchable generically -- still calls straight into
-- the same generic auto_fed_recompute, no rule-specific logic here.
CREATE OR REPLACE FUNCTION auto_fed_dispatch_entity_relationships() RETURNS trigger AS $$
DECLARE
  v_child_id uuid := COALESCE(NEW.child_entity_id, OLD.child_entity_id);
  v_old_child_id uuid := OLD.child_entity_id;
BEGIN
  PERFORM auto_fed_recompute(reg.id, v_child_id)
  FROM auto_fed_registries reg
  WHERE reg.source_table_name = 'entities' AND reg.is_active
    AND reg.company_id = (SELECT company_id FROM entities WHERE id = v_child_id);
  IF TG_OP = 'UPDATE' AND v_old_child_id IS DISTINCT FROM NEW.child_entity_id THEN
    PERFORM auto_fed_recompute(reg.id, v_old_child_id)
    FROM auto_fed_registries reg
    WHERE reg.source_table_name = 'entities' AND reg.is_active
      AND reg.company_id = (SELECT company_id FROM entities WHERE id = v_old_child_id);
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_niksen_entity_relationships_irregularities ON entity_relationships;
DROP TRIGGER IF EXISTS trg_auto_fed_dispatch_entity_relationships ON entity_relationships;
CREATE TRIGGER trg_auto_fed_dispatch_entity_relationships
AFTER INSERT OR UPDATE OR DELETE ON entity_relationships
FOR EACH ROW EXECUTE FUNCTION auto_fed_dispatch_entity_relationships();

-- company_custom_field_values is high-traffic/all-companies -- keep this
-- dispatch as cheap as possible for every write that isn't a watched field.
CREATE OR REPLACE FUNCTION auto_fed_dispatch_custom_field_values() RETURNS trigger AS $$
DECLARE
  v_row company_custom_field_values := COALESCE(NEW, OLD);
  v_field company_custom_fields;
  v_registry_id uuid;
BEGIN
  SELECT * INTO v_field FROM company_custom_fields WHERE id = v_row.field_id;
  IF NOT FOUND THEN RETURN v_row; END IF;
  FOR v_registry_id IN
    SELECT id FROM auto_fed_registries WHERE source_table_name = v_field.table_name AND company_id = v_field.company_id AND is_active
  LOOP
    PERFORM auto_fed_recompute(v_registry_id, v_row.record_id);
  END LOOP;
  RETURN v_row;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_niksen_ccfv_irregularities ON company_custom_field_values;
DROP TRIGGER IF EXISTS trg_auto_fed_dispatch_ccfv ON company_custom_field_values;
CREATE TRIGGER trg_auto_fed_dispatch_ccfv
AFTER INSERT OR UPDATE OR DELETE ON company_custom_field_values
FOR EACH ROW EXECUTE FUNCTION auto_fed_dispatch_custom_field_values();

-- ── Retire the old Niksen-specific engine (superseded by the above) ──
DROP TRIGGER IF EXISTS trg_niksen_entities_irregularities ON entities;
DROP FUNCTION IF EXISTS niksen_entities_irregularity_trigger();
DROP FUNCTION IF EXISTS niksen_recompute_entity_irregularities(uuid);
DROP FUNCTION IF EXISTS niksen_upsert_irregularity(uuid, uuid, uuid, uuid, uuid, uuid, uuid, uuid, uuid, uuid, uuid, text, text, text, text, text, boolean);
DROP FUNCTION IF EXISTS niksen_is_valid_abn(text);
DROP FUNCTION IF EXISTS niksen_is_valid_acn(text);
DROP FUNCTION IF EXISTS niksen_is_valid_tfn(text);
