-- Fixes the same cross-tenant RLS leak as the tasks migration
-- (20260803050000), found to be systemic across ~65 more tables: every one
-- scoped visibility to "any company the caller is a member of" (via a
-- `company_id IN (SELECT company_id FROM company_memberships WHERE user_id =
-- auth.uid())` subquery, or the same check one join away through a parent
-- table), not the caller's currently ACTIVE company. A user who belongs to
-- 2+ companies saw/could write a UNION of data across every company they
-- belong to, regardless of which one was active -- same root cause as
-- tasks, just far more widespread (precedents, client update pages,
-- document templates, teams/WhatsApp/OneDrive/Xero bot config, virtual
-- computers, task_watchers/task_follow_ups/task_activity_log, the template
-- marketplace, etc).
--
-- Fix: swap that membership subquery for `(SELECT active_company_id())` --
-- `X IN (SELECT active_company_id())` is exactly equivalent to `X =
-- active_company_id()` since the function returns a single scalar, so this
-- is a pure substitution, not a rewrite of any policy's actual logic.
-- Role-gated variants (`... AND role = 'company_admin'`) become `(SELECT
-- active_company_id() WHERE is_current_user_admin())` -- same substitution
-- idea, reusing the existing (already correctly active-company-scoped)
-- admin-check helper instead of duplicating a membership+role join.
--
-- Two policies needed individual handling instead of the mechanical swap:
--   - company_default_views_admin correlated directly against the ROW's own
--     company_id (not a blanket membership check) -- replaced with the
--     equivalent-but-simpler `row.company_id = active_company_id() AND
--     is_current_user_admin()`.
--   - project_members_admin/read, project_teams_admin/read intentionally
--     left UNCHANGED: they correlate against the parent PROJECT's own
--     company_id, and `projects` itself is already strictly scoped to
--     active_company_id() -- you can never even reference a project_id
--     outside your active company to begin with, so these were already
--     safe, just via a different (equally valid) mechanism.
--
-- Every other statement below is a mechanical substitution over the live
-- policy text (generated by re-fetching pg_policy and regex-substituting
-- the exact membership subquery, not hand-transcribed), reviewed in full
-- before being applied. ctvl_* (company_table_value_links) also has a
-- correlated-EXISTS-per-row performance anti-pattern like ctf/ctr/ctv
-- (20260803060000) -- left as-is here since this migration is scoped to the
-- cross-tenant fix, not performance; a smaller/rarer table than ctv so
-- lower urgency, worth a follow-up.

ALTER POLICY ai_chat_settings_company_members ON ai_chat_settings
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY ai_conversations_owner ON ai_conversations
  USING ((user_id = auth.uid()))
  WITH CHECK (((user_id = auth.uid()) AND (company_id IN (SELECT active_company_id()))));

ALTER POLICY ai_document_chunks_company_members ON ai_document_chunks
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY ai_embed_cursors_company_members ON ai_embed_cursors
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY ai_usage_events_company_members ON ai_usage_events
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY auto_fed_registries_rw ON auto_fed_registries
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY auto_fed_rules_rw ON auto_fed_rules
  USING ((registry_id IN ( SELECT auto_fed_registries.id
   FROM auto_fed_registries
  WHERE (auto_fed_registries.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((registry_id IN ( SELECT auto_fed_registries.id
   FROM auto_fed_registries
  WHERE (auto_fed_registries.company_id IN (SELECT active_company_id())))));

ALTER POLICY bot_created_files_company_members ON bot_created_files
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY client_update_auto_add_rules_rw ON client_update_auto_add_rules
  USING ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_groups_company_members ON client_update_groups
  USING ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_ai_field_flags_company_members ON client_update_page_ai_field_flags
  USING ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_emails_company_members ON client_update_page_emails
  USING ((item_id IN ( SELECT i.id
   FROM (client_update_page_items i
     JOIN client_update_pages p ON ((p.id = i.page_id)))
  WHERE (p.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((item_id IN ( SELECT i.id
   FROM (client_update_page_items i
     JOIN client_update_pages p ON ((p.id = i.page_id)))
  WHERE (p.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_fields_company_members ON client_update_page_fields
  USING ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_format_rules_company_members ON client_update_page_format_rules
  USING ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_items_company_members ON client_update_page_items
  USING ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_logs_company_members ON client_update_page_logs
  USING ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_notes_company_members ON client_update_page_notes
  USING ((item_id IN ( SELECT i.id
   FROM (client_update_page_items i
     JOIN client_update_pages p ON ((p.id = i.page_id)))
  WHERE (p.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((item_id IN ( SELECT i.id
   FROM (client_update_page_items i
     JOIN client_update_pages p ON ((p.id = i.page_id)))
  WHERE (p.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_teams_company_members ON client_update_page_teams
  USING ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT client_update_pages.id
   FROM client_update_pages
  WHERE (client_update_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_page_values_company_members ON client_update_page_values
  USING ((item_id IN ( SELECT i.id
   FROM (client_update_page_items i
     JOIN client_update_pages p ON ((p.id = i.page_id)))
  WHERE (p.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((item_id IN ( SELECT i.id
   FROM (client_update_page_items i
     JOIN client_update_pages p ON ((p.id = i.page_id)))
  WHERE (p.company_id IN (SELECT active_company_id())))));

ALTER POLICY client_update_pages_company_members ON client_update_pages
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY addon_config_company ON company_addon_config
  USING ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_cloud_credentials_company_members ON company_cloud_credentials
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_deed_templates_select ON company_deed_templates
  USING ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_default_views_admin ON company_default_views
  USING ((company_default_views.company_id = active_company_id() AND is_current_user_admin()));

ALTER POLICY company_default_views_read ON company_default_views
  USING ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_email_domains_company_members ON company_email_domains
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_execution_templates_select ON company_execution_templates
  USING ((company_id IN (SELECT active_company_id())));

ALTER POLICY field_constraints_admin ON company_field_constraints
  USING ((company_id IN (SELECT active_company_id() WHERE is_current_user_admin())));

ALTER POLICY company_letterheads_company_members ON company_letterheads
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_onedrive_credentials_company_members ON company_onedrive_credentials
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_record_tab_defaults_members ON company_record_tab_defaults
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_subscriptions_company_members ON company_subscriptions
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_table_field_sections_company_members ON company_table_field_sections
  USING ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_table_record_log_read ON company_table_record_log
  USING ((company_id IN (SELECT active_company_id())));

ALTER POLICY ctvl_delete ON company_table_value_links
  USING (((company_id IN (SELECT active_company_id())) AND (EXISTS ( SELECT 1
   FROM (company_table_records ctr
     JOIN company_tables ct ON ((ct.id = ctr.table_id)))
  WHERE ((ctr.id = company_table_value_links.record_id) AND ((ct.owner_user_id = auth.uid()) OR is_current_user_admin() OR (user_resource_role('table'::text, ct.id) = ANY (ARRAY['editor'::text, 'admin'::text])) OR ((ct.owner_user_id IS NULL) AND (NOT resource_has_explicit_permissions('table'::text, ct.id)) AND (NOT company_restricts_new_resources_by_default(ct.company_id)))))))));

ALTER POLICY ctvl_insert ON company_table_value_links
  WITH CHECK (((company_id IN (SELECT active_company_id())) AND (EXISTS ( SELECT 1
   FROM (company_table_records ctr
     JOIN company_tables ct ON ((ct.id = ctr.table_id)))
  WHERE ((ctr.id = company_table_value_links.record_id) AND ((ct.owner_user_id = auth.uid()) OR is_current_user_admin() OR (user_resource_role('table'::text, ct.id) = ANY (ARRAY['editor'::text, 'admin'::text])) OR ((ct.owner_user_id IS NULL) AND (NOT resource_has_explicit_permissions('table'::text, ct.id)) AND (NOT company_restricts_new_resources_by_default(ct.company_id)))))))));

ALTER POLICY ctvl_select ON company_table_value_links
  USING (((company_id IN (SELECT active_company_id())) AND (EXISTS ( SELECT 1
   FROM (company_table_records ctr
     JOIN company_tables ct ON ((ct.id = ctr.table_id)))
  WHERE ((ctr.id = company_table_value_links.record_id) AND ((ct.owner_user_id = auth.uid()) OR is_current_user_admin() OR (user_resource_role('table'::text, ct.id) IS NOT NULL) OR ((ct.owner_user_id IS NULL) AND (NOT resource_has_explicit_permissions('table'::text, ct.id)) AND (NOT company_restricts_new_resources_by_default(ct.company_id)))))))));

ALTER POLICY ctvl_update ON company_table_value_links
  USING (((company_id IN (SELECT active_company_id())) AND (EXISTS ( SELECT 1
   FROM (company_table_records ctr
     JOIN company_tables ct ON ((ct.id = ctr.table_id)))
  WHERE ((ctr.id = company_table_value_links.record_id) AND ((ct.owner_user_id = auth.uid()) OR is_current_user_admin() OR (user_resource_role('table'::text, ct.id) = ANY (ARRAY['editor'::text, 'admin'::text])) OR ((ct.owner_user_id IS NULL) AND (NOT resource_has_explicit_permissions('table'::text, ct.id)) AND (NOT company_restricts_new_resources_by_default(ct.company_id)))))))))
  WITH CHECK (((company_id IN (SELECT active_company_id())) AND (EXISTS ( SELECT 1
   FROM (company_table_records ctr
     JOIN company_tables ct ON ((ct.id = ctr.table_id)))
  WHERE ((ctr.id = company_table_value_links.record_id) AND ((ct.owner_user_id = auth.uid()) OR is_current_user_admin() OR (user_resource_role('table'::text, ct.id) = ANY (ARRAY['editor'::text, 'admin'::text])) OR ((ct.owner_user_id IS NULL) AND (NOT resource_has_explicit_permissions('table'::text, ct.id)) AND (NOT company_restricts_new_resources_by_default(ct.company_id)))))))));

ALTER POLICY company_teams_bot_credentials_company_members ON company_teams_bot_credentials
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_teams_credentials_company_members ON company_teams_credentials
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_template_dashboard_map_company_members ON company_template_dashboard_map
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_template_field_map_company_members ON company_template_field_map
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_template_installs_company_members ON company_template_installs
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_template_table_map_company_members ON company_template_table_map
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_vm_schedules_company_members ON company_vm_schedules
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_whatsapp_credentials_company_members ON company_whatsapp_credentials
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY company_xero_connections_company_members ON company_xero_connections
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY document_fill_generated_files_company_members ON document_fill_generated_files
  USING ((submission_id IN ( SELECT s.id
   FROM (document_fill_submissions s
     JOIN document_fill_pages p ON ((p.id = s.page_id)))
  WHERE (p.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((submission_id IN ( SELECT s.id
   FROM (document_fill_submissions s
     JOIN document_fill_pages p ON ((p.id = s.page_id)))
  WHERE (p.company_id IN (SELECT active_company_id())))));

ALTER POLICY document_fill_page_templates_company_members ON document_fill_page_templates
  USING ((page_id IN ( SELECT document_fill_pages.id
   FROM document_fill_pages
  WHERE (document_fill_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT document_fill_pages.id
   FROM document_fill_pages
  WHERE (document_fill_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY document_fill_pages_company_members ON document_fill_pages
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY document_fill_submissions_company_members ON document_fill_submissions
  USING ((page_id IN ( SELECT document_fill_pages.id
   FROM document_fill_pages
  WHERE (document_fill_pages.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((page_id IN ( SELECT document_fill_pages.id
   FROM document_fill_pages
  WHERE (document_fill_pages.company_id IN (SELECT active_company_id())))));

ALTER POLICY document_template_fields_company_members ON document_template_fields
  USING ((template_id IN ( SELECT document_templates.id
   FROM document_templates
  WHERE (document_templates.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((template_id IN ( SELECT document_templates.id
   FROM document_templates
  WHERE (document_templates.company_id IN (SELECT active_company_id())))));

ALTER POLICY document_templates_company_members ON document_templates
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY email_log_company_members ON email_log
  USING ((company_id IN (SELECT active_company_id())));

ALTER POLICY finance_model_attachments_write ON finance_model_attachments
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY finance_model_budget_categories_write ON finance_model_budget_categories
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY finance_model_loan_allocations_company_members ON finance_model_loan_allocations
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY import_jobs_company ON label_import_jobs
  USING ((company_id IN (SELECT active_company_id())));

ALTER POLICY lead_emails_company_members ON lead_emails
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY lead_gmail_labels_company_members ON lead_gmail_labels
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY onedrive_files_company_members ON onedrive_files
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY outlook_sync_jobs_company_members ON outlook_sync_jobs
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY outlook_sync_log_company_members ON outlook_sync_log
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY pdf_documents_company_members ON pdf_documents
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY precedent_body_examples_company_members ON precedent_body_examples
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY precedent_issuances_company_members ON precedent_issuances
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY precedent_settings_company_members ON precedent_settings
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY precedent_signoff_request_signers_company_members ON precedent_signoff_request_signers
  USING ((request_id IN ( SELECT precedent_signoff_requests.id
   FROM precedent_signoff_requests
  WHERE (precedent_signoff_requests.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((request_id IN ( SELECT precedent_signoff_requests.id
   FROM precedent_signoff_requests
  WHERE (precedent_signoff_requests.company_id IN (SELECT active_company_id())))));

ALTER POLICY precedent_signoff_requests_company_members ON precedent_signoff_requests
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY precedents_company_members ON precedents
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY project_outlook_emails_company_members ON project_outlook_emails
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY project_outlook_labels_company_members ON project_outlook_labels
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY project_properties_company_members ON project_properties
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY project_property_values_company_members ON project_property_values
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY record_tab_dashboard_widgets_company_members ON record_tab_dashboard_widgets
  USING ((tab_id IN ( SELECT record_tabs.id
   FROM record_tabs
  WHERE (record_tabs.company_id IN (SELECT active_company_id())))))
  WITH CHECK ((tab_id IN ( SELECT record_tabs.id
   FROM record_tabs
  WHERE (record_tabs.company_id IN (SELECT active_company_id())))));

ALTER POLICY schema_change_log_company_members ON schema_change_log
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY sms_messages_company_members ON sms_messages
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY staff_signoffs_company_members ON staff_signoffs
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY task_activity_log_company_members ON task_activity_log
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY task_dependencies_company_members ON task_dependencies
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY task_follow_ups_company_members ON task_follow_ups
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY task_group_overrides_company_members ON task_group_overrides
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY task_teams_company_members ON task_teams
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY task_watchers_company_members ON task_watchers
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY teams_write ON teams
  USING ((company_id IN (SELECT active_company_id() WHERE is_current_user_admin())))
  WITH CHECK ((company_id IN (SELECT active_company_id() WHERE is_current_user_admin())));

ALTER POLICY teams_bot_action_field_settings_company_members ON teams_bot_action_field_settings
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY teams_bot_linked_accounts_owner ON teams_bot_linked_accounts
  USING ((user_id = auth.uid()))
  WITH CHECK (((user_id = auth.uid()) AND (company_id IN (SELECT active_company_id()))));

ALTER POLICY teams_bot_project_search_fields_company_members ON teams_bot_project_search_fields
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY teams_messages_company_members ON teams_messages
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY teams_sync_cursors_company_members ON teams_sync_cursors
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY template_definition_dashboards_rw ON template_definition_dashboards
  USING ((template_id IN ( SELECT template_definitions.id
   FROM template_definitions
  WHERE (template_definitions.is_published OR (template_definitions.owner_company_id IN (SELECT active_company_id()))))))
  WITH CHECK ((template_id IN ( SELECT template_definitions.id
   FROM template_definitions
  WHERE (template_definitions.owner_company_id IN (SELECT active_company_id() WHERE is_current_user_admin())))));

ALTER POLICY template_definition_system_fields_rw ON template_definition_system_fields
  USING ((template_id IN ( SELECT template_definitions.id
   FROM template_definitions
  WHERE (template_definitions.is_published OR (template_definitions.owner_company_id IN (SELECT active_company_id()))))))
  WITH CHECK ((template_id IN ( SELECT template_definitions.id
   FROM template_definitions
  WHERE (template_definitions.owner_company_id IN (SELECT active_company_id() WHERE is_current_user_admin())))));

ALTER POLICY template_definition_table_fields_rw ON template_definition_table_fields
  USING ((template_table_id IN ( SELECT tt.id
   FROM (template_definition_tables tt
     JOIN template_definitions td ON ((td.id = tt.template_id)))
  WHERE (td.is_published OR (td.owner_company_id IN (SELECT active_company_id()))))))
  WITH CHECK ((template_table_id IN ( SELECT tt.id
   FROM (template_definition_tables tt
     JOIN template_definitions td ON ((td.id = tt.template_id)))
  WHERE (td.owner_company_id IN (SELECT active_company_id() WHERE is_current_user_admin())))));

ALTER POLICY template_definition_tables_rw ON template_definition_tables
  USING ((template_id IN ( SELECT template_definitions.id
   FROM template_definitions
  WHERE (template_definitions.is_published OR (template_definitions.owner_company_id IN (SELECT active_company_id()))))))
  WITH CHECK ((template_id IN ( SELECT template_definitions.id
   FROM template_definitions
  WHERE (template_definitions.owner_company_id IN (SELECT active_company_id() WHERE is_current_user_admin())))));

ALTER POLICY template_definitions_delete ON template_definitions
  USING ((owner_company_id IN (SELECT active_company_id() WHERE is_current_user_admin())));

ALTER POLICY template_definitions_read ON template_definitions
  USING ((is_published OR (owner_company_id IN (SELECT active_company_id()))));

ALTER POLICY template_definitions_update ON template_definitions
  USING ((owner_company_id IN (SELECT active_company_id() WHERE is_current_user_admin())))
  WITH CHECK ((owner_company_id IN (SELECT active_company_id() WHERE is_current_user_admin())));

ALTER POLICY template_definitions_write ON template_definitions
  WITH CHECK ((owner_company_id IN (SELECT active_company_id() WHERE is_current_user_admin())));

ALTER POLICY user_saved_views_company_members ON user_saved_views
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY virtual_computer_usage_events_company_members ON virtual_computer_usage_events
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY virtual_computers_company_members ON virtual_computers
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY whatsapp_bot_groups_company_members ON whatsapp_bot_groups
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY whatsapp_bot_linked_accounts_company_members ON whatsapp_bot_linked_accounts
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));

ALTER POLICY whatsapp_messages_company_members ON whatsapp_messages
  USING ((company_id IN (SELECT active_company_id())))
  WITH CHECK ((company_id IN (SELECT active_company_id())));
